modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"

[[mods]]
modId = "spellbladenext"
version = "${version}"
displayName = "Spellblades and Such"
authors = "Me!"
description = '''
Spellblades and Such is a spell engine addon that adds magic enhanced bladed weaponry!
'''
logoFile = "assets/spellbladenext/icon.png"

[[dependencies.spellbladenext]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spellbladenext]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spellbladenext]]
modId = "forgified_fabric_api"
type = "required"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.spellbladenext]]
modId = "spell_engine"
type = "required"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.spellbladenext]]
modId = "spell_power"
type = "required"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[mixins]]
config = "spellbladenext.mixins.json"
